  0%|          | 0/82 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/Student/s4820129/PatternAnalysis-2023/lesion_segmentation_s4820129/train.py", line 38, in <module>
    for image, truth in progress_bar:
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4820129/miniconda3/envs/cluster_env/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/Student/s4820129/PatternAnalysis-2023/lesion_segmentation_s4820129/dataset.py", line 29, in __getitem__
    image, truth = self.transform(image, truth)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not callable